version: '3'

services:

  nodeapp:
    build: 
      context: node
    container_name: nodeapp
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - nodenet

  nodedb:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: nodedb
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet

networks:
  nodenet: 
    driver: bridge