version: '3'

services:
  nodedb:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: nodedb
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/mysql:/docker-entrypoint-initdb.d
    networks:
      - nodenet

  nodeapp:
    build: 
      context: node
    container_name: nodeapp
    restart: always
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
    depends_on:
      - nodedb
    networks:
      - nodenet

  nodenginx:
    build:
      context: nginx
    container_name: nodenginx
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeapp
    networks:
      - nodenet

networks:
  nodenet: 
    driver: bridge